# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - var='new_header = "https://buymymojo.gitlab.io/buymymojo-hugo/"'
  - sed -i.bak "1 s/.*/$new_header/" config.toml
  - cat config.toml
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
